package com.zhxh.core.exception;

public enum ErrorCode {
    ERROR_UNKNOWN_EXCEPTION,
    ERROR_DATA_ALREADY_EXISTS,
    ERROR_DATA_NOT_EXISTS,
    ERROR_ROOT_CANNOT_DELETE,

    ERROR_GRANT_PRIVILEGE_FAILED,
    ERROR_REVOKE_PRIVILEGE_FAILED,
}

